#Vault
spring.application.name=docker
spring.config.import=vault://
spring.cloud.vault.uri=http://10.4.72.9:8200
spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.ssl.enabled=false
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.backend-version=2
spring.cloud.vault.kv.default-context=docker

#DB
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.use-new-id-generator-mappings= false
spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=none
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool-1


#Spring Cloud
spring.cloud.compatibility-verifier.enabled=false


#Kafka
spring.kafka.bootstrap-servers=10.4.72.9:9096,10.4.72.9:9097,10.4.72.9:9098
com.dt.kafka.topic.central=central-log-topic
com.dt.kafka.ra.topic=ra-logs-topic


#External URL's
ra.service.issueCertificateCallbackURL = http://10.4.72.7:7017/api/post/service/certificate/request/callback
ra.service.pki = http://10.4.72.7:7080/PKIServiceTransactionHandler/transaction-handler/post/service/process-transaction
ra.service.status = http://10.4.72.7:7080/PKIServiceTransactionHandler/transaction-handler/get/service/status
ra.service.notification = http://10.4.72.7:7014/send/notification
email.url= http://10.4.72.7:5005/sendemail
email.user=ram@gmail.com
url.unlocked.AuthResetPin=https://staging.digitaltrusttech.com:44319/api/Authentication/ActivateSubscriber


#Sentry
sentry.dsn=https://aa960d7a068a43ad808a148e929be532@monitor.digitaltrusttech.com/27
sentry.environment=staging
sentry.traces-sample-rate=1.0
sentry.exception-resolver-order=-2147483647
sentry.debug=false
sentry.logging.minimum-event-level=info
sentry.logging.minimum-breadcrumb-level=debug


# Servelet
server.compression.enabled=true
server.compression.min-response-size=2048
server.compression.mime-types=text/html,text/xml,text/plain,application/json,application/javascript
spring.banner.location=classpath:/banner.txt
allowedOrigins=*
allowedMethods=HEAD,GET,POST,PUT,DELETE,PATCH,OPTIONS



#Configurations
ugpass.code=false
device.update.policy=2
base64.pdf = ""
com.dt.pin.history.size=3



